# Generated by Django 4.2.6 on 2023-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/pic2.jpg', upload_to='test/'),
        ),
    ]
